[phases.setup]
nixPkgs = ["nodejs", "python312", "file", "zlib"]

[phases.install]
dependsOn = ["setup"]
# Dynamically get the path to the 'file' package's lib directory and add it to LD_LIBRARY_PATH
# This command specifically gets the output path of the 'file' package.
# The 'install' phase ensures this environment variable is set BEFORE pip installs and Django runs.
env = { LD_LIBRARY_PATH = "$(nix-build '<nixpkgs>' -A file --no-out-link)/lib:$LD_LIBRARY_PATH" }
cmd = "pip install -r requirements.txt"

# Make sure you've removed the [phases.start] section if you're using a Procfile.