[phases.setup]
nixPkgs = ["file", "gcc", "nodejs"]

[phases.install]
cmds = ["pip install -r requirements.txt", "npm install"]

[phases.build]
cmds = ["npm run build-prod", "python manage.py collectstatic --noinput"]

[start]
cmd = "python manage.py migrate && gunicorn casestudy_project.wsgi:application --bind 0.0.0.0:$PORT" 