[phases.setup]
nixPkgs = ["nodejs", "file", "zlib"]

[phases.install]
dependsOn = ["setup"]
env = { LD_LIBRARY_PATH = "/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH" }
# ONLY install Python requirements here.
# collectstatic and migrate are handled by your Railway pre-deploy command.
cmd = "pip install -r requirements.txt"

# Ensure this section is removed if you're using a Procfile for start command
# [phases.start]
# cmd = "python manage.py runserver 0.0.0.0:$PORT"