# Generated by Django 4.2.14 on 2025-06-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main heading for the notification pop-up.', max_length=200)),
                ('body', models.TextField(help_text='Body text for the notification pop-up.')),
                ('video', models.FileField(blank=True, help_text='Optional video for the notification pop-up.', null=True, upload_to='notifications/')),
                ('button_text', models.CharField(default='Share', help_text='Text for the notification button.', max_length=100)),
                ('button_link', models.URLField(blank=True, help_text='URL the button should link to.', max_length=300)),
                ('is_active', models.BooleanField(default=True, help_text='Show this notification on the homepage?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
