# Generated by Django 5.2.3 on 2025-06-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='short_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
