# Generated by Django 5.2.3 on 2025-06-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0002_casestudy_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudy',
            name='content',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='short_description',
        ),
        migrations.AddField(
            model_name='casestudy',
            name='case_background',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='data_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Easy', max_length=20),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='domain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='expert_solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='task',
            field=models.TextField(blank=True),
        ),
    ]
