# Generated by Django 5.2.3 on 2025-06-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0003_remove_casestudy_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='loves',
            field=models.IntegerField(default=0),
        ),
    ]
