# Generated by Django 4.2.14 on 2025-06-27 03:01

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0003_notification_delay_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='expert_solution',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
