# Generated by Django 5.2.3 on 2025-06-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0004_casestudy_loves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='thumbnail',
            field=models.ImageField(help_text='For best results, use an image that is 370px wide by 160px tall.', upload_to='thumbnails/'),
        ),
    ]
