# Generated by Django 4.2.14 on 2025-06-27 05:26

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0005_alter_casestudy_options_casestudy_admin_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmittedCaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('submitter_email', models.EmailField(help_text='Email of the person submitting the case study', max_length=254)),
                ('domain', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('tags', models.TextField(blank=True, help_text='Comma-separated tags')),
                ('case_background', django_ckeditor_5.fields.CKEditor5Field()),
                ('task', django_ckeditor_5.fields.CKEditor5Field()),
                ('expert_solution', django_ckeditor_5.fields.CKEditor5Field()),
                ('options', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('is_approved', models.BooleanField(blank=True, help_text='True=Approved, False=Rejected, Null=Pending', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from admin about approval/rejection')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Submitted Case Study',
                'verbose_name_plural': 'User Submitted Case Studies',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
