# Generated by Django 5.2.3 on 2025-06-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0005_alter_casestudy_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='summary_image1',
            field=models.ImageField(blank=True, null=True, upload_to='summary_images/'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='summary_image2',
            field=models.ImageField(blank=True, null=True, upload_to='summary_images/'),
        ),
    ]
