# Generated by Django 4.2.14 on 2025-06-27 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0006_usersubmittedcasestudy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudy',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='submitter_email',
        ),
    ]
