# Generated by Django 5.2.3 on 2025-06-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0006_casestudy_summary_image1_casestudy_summary_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudy',
            name='summary_image1',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='summary_image2',
        ),
        migrations.AddField(
            model_name='casestudy',
            name='dataset',
            field=models.FileField(blank=True, help_text='Upload the dataset file (CSV, Excel, etc.)', null=True, upload_to='datasets/'),
        ),
    ]
