# Generated by Django 4.2.14 on 2025-06-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0007_remove_casestudy_admin_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmittedcasestudy',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
