# Generated by Django 5.2.3 on 2025-06-22 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0007_remove_casestudy_summary_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestudy',
            name='loves',
        ),
    ]
