# Generated by Django 4.2.14 on 2025-06-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0009_usersubmittedcasestudy_dataset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmittedcasestudy',
            name='options',
            field=models.TextField(blank=True),
        ),
    ]
