# Generated by Django 5.2.3 on 2025-06-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0009_casestudy_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='author',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
