# Generated by Django 5.2.3 on 2025-06-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0010_alter_casestudy_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='thumbnail',
            field=models.ImageField(help_text='For best results, use an image that is 1584px wide by 396px tall and content centered.', upload_to='thumbnails/'),
        ),
    ]
