# Generated by Django 4.2.14 on 2025-06-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0010_alter_usersubmittedcasestudy_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmittedcasestudy',
            name='domain',
            field=models.CharField(choices=[('Business & Marketing', 'Business & Marketing'), ('Sales & Revenue', 'Sales & Revenue'), ('Finance', 'Finance'), ('Healthcare & Medical', 'Healthcare & Medical'), ('Retail & E-commerce', 'Retail & E-commerce'), ('Web & App', 'Web & App'), ('Social Media & Influencer', 'Social Media & Influencer'), ('Supply Chain & Logistics', 'Supply Chain & Logistics'), ('Education', 'Education'), ('Government & Public Sector', 'Government & Public Sector'), ('Manufacturing & Operations', 'Manufacturing & Operations'), ('Energy & Environment', 'Energy & Environment'), ('Real Estate & Property', 'Real Estate & Property'), ('Sports & Fitness', 'Sports & Fitness')], max_length=100),
        ),
    ]
