# Generated by Django 5.2.3 on 2025-06-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0011_alter_casestudy_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags (e.g., SQL, Python, EDA, Business)', max_length=500),
        ),
    ]
