# Generated by Django 4.2.14 on 2025-06-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0012_usersubmittedcasestudy_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
    ]
