# Generated by Django 5.2.3 on 2025-06-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0012_casestudy_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='author_url',
            field=models.URLField(blank=True, help_text="URL for the author's profile or website.", null=True),
        ),
    ]
