# Generated by Django 4.2.14 on 2025-06-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0013_alter_casestudy_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField()),
                ('email', models.EmailField(max_length=254)),
                ('dataset', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Upload Log',
                'verbose_name_plural': 'Upload Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
