# Generated by Django 4.2.14 on 2025-06-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casestudies', '0014_uploadlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='video',
        ),
    ]
