name: Run Django Migrations on Railway

on:
  push:
    branches:
      - master

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: curl -fsSL https://railway.com/install.sh | sh

      - name: Set up Railway project link
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway link -p 569f0d9c-028a-48e2-a7ca-1d50509795c5 -e production

      - name: Run migrations on Railway service
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway run --service casestudies python manage.py migrate
