name: Run Django Migrations on Railway

on:
  push:
    branches:
      - master

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: curl -fsSL https://railway.com/install.sh | sh

      - name: Run migrations on Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway run python manage.py migrate
